// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFB3uewLMuM9L6ikFKwHzSOhh5vpq3Vs',
    appId: '1:634536916714:web:7e6ef886eb46df2a300993',
    messagingSenderId: '634536916714',
    projectId: 'chat-51364',
    authDomain: 'chat-51364.firebaseapp.com',
    storageBucket: 'chat-51364.firebasestorage.app',
    measurementId: 'G-NYGVTZK13F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKvWpEETw6bNjuCF2l2BcCwTsiwgvnMQ',
    appId: '1:634536916714:android:bfdb620b2186bdef300993',
    messagingSenderId: '634536916714',
    projectId: 'chat-51364',
    storageBucket: 'chat-51364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3AuxgY3FHDrrHAlxFgzWC9y8z7gYFvQ',
    appId: '1:634536916714:ios:6839942ee3f836be300993',
    messagingSenderId: '634536916714',
    projectId: 'chat-51364',
    storageBucket: 'chat-51364.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3AuxgY3FHDrrHAlxFgzWC9y8z7gYFvQ',
    appId: '1:634536916714:ios:6839942ee3f836be300993',
    messagingSenderId: '634536916714',
    projectId: 'chat-51364',
    storageBucket: 'chat-51364.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJFB3uewLMuM9L6ikFKwHzSOhh5vpq3Vs',
    appId: '1:634536916714:web:5c761e68f43c9dcc300993',
    messagingSenderId: '634536916714',
    projectId: 'chat-51364',
    authDomain: 'chat-51364.firebaseapp.com',
    storageBucket: 'chat-51364.firebasestorage.app',
    measurementId: 'G-Q6B70H32QJ',
  );

}